plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.dervarex.minified.launch'

description = 'Launch/runtime utilities'

repositories {
    mavenCentral()
    mavenLocal()

    maven {
        url = 'https://repo.opencollab.dev/main/'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
dependencies {
    implementation 'com.dervarex.minified.utils:minified-utils:1.0.0' // currently local only - todo: publish to maven central
    compileOnly 'org.jetbrains:annotations:24.1.0'
}