plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.dervarex.minified.utils'

description = 'General utilities'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
