plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.dervarex.minified.auth'
version = '1.0.0'

description = 'Authentication utilities'

repositories {
    mavenCentral()
    mavenLocal()

    maven {
        url = 'https://repo.opencollab.dev/main/'
    }
}

dependencies {
    implementation 'net.raphimc:MinecraftAuth:4.1.2'

    api "net.lenni0451.commons:httpclient:1.7.1"
    api "net.lenni0451.commons:gson:1.9.2"
    api project(':minified-java')

    compileOnly 'org.jetbrains:annotations:24.1.0'

    implementation(project(":minified-utils"))
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    enabled = true
    testLogging {
        showStandardStreams = true
        events "passed", "failed", "skipped", "standardOut", "standardError"
    }
}

test {
    useJUnitPlatform {
        excludeTags("manual")
    }

    failOnNoDiscoveredTests = false
}

tasks.register("manualTest", Test) {
    useJUnitPlatform {
        includeTags("manual")
    }

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}